export const permissionActions = ['view', 'create', 'edit', 'delete', 'approve', 'export', 'upload', 'download'] as const;

export type PermissionAction = (typeof permissionActions)[number];

export const contractPermissions = [
  { action: 'view', code: 'work_orders.view', name: 'View Work Orders', resource: 'Work Orders' },
  { action: 'create', code: 'work_orders.create', name: 'Create Work Orders', resource: 'Work Orders' },
  { action: 'edit', code: 'work_orders.edit', name: 'Edit Work Orders', resource: 'Work Orders' },
  { action: 'delete', code: 'work_orders.delete', name: 'Delete Work Orders', resource: 'Work Orders' },
  { action: 'approve', code: 'work_orders.approve', name: 'Approve Work Orders', resource: 'Work Orders' },
  { action: 'export', code: 'work_orders.export', name: 'Export Work Orders', resource: 'Work Orders' },
  { action: 'view', code: 'ra_bills.view', name: 'View RA Bills', resource: 'RA Bills' },
  { action: 'create', code: 'ra_bills.create', name: 'Create RA Bills', resource: 'RA Bills' },
  { action: 'edit', code: 'ra_bills.edit', name: 'Edit RA Bills', resource: 'RA Bills' },
  { action: 'delete', code: 'ra_bills.delete', name: 'Delete RA Bills', resource: 'RA Bills' },
  { action: 'approve', code: 'ra_bills.approve', name: 'Approve RA Bills', resource: 'RA Bills' },
  { action: 'export', code: 'ra_bills.export', name: 'Export RA Bills', resource: 'RA Bills' },
  { action: 'view', code: 'invoices.view', name: 'View Invoices', resource: 'Invoices' },
  { action: 'create', code: 'invoices.create', name: 'Create Invoices', resource: 'Invoices' },
  { action: 'edit', code: 'invoices.edit', name: 'Edit Invoices', resource: 'Invoices' },
  { action: 'delete', code: 'invoices.delete', name: 'Delete Invoices', resource: 'Invoices' },
  { action: 'approve', code: 'invoices.verify', name: 'Verify Invoices', resource: 'Invoices' },
  { action: 'export', code: 'invoices.export', name: 'Export Invoices', resource: 'Invoices' },
  { action: 'view', code: 'payments.view', name: 'View Payments', resource: 'Payments' },
  { action: 'create', code: 'payments.create', name: 'Create Payments', resource: 'Payments' },
  { action: 'edit', code: 'payments.edit', name: 'Edit Payments', resource: 'Payments' },
  { action: 'delete', code: 'payments.delete', name: 'Delete Payments', resource: 'Payments' },
  { action: 'approve', code: 'payments.approve', name: 'Approve Payments', resource: 'Payments' },
  { action: 'export', code: 'payments.export', name: 'Export Payments', resource: 'Payments' },
  { action: 'view', code: 'debit_notes.view', name: 'View Debit Notes', resource: 'Debit Notes' },
  { action: 'create', code: 'debit_notes.create', name: 'Create Debit Notes', resource: 'Debit Notes' },
  { action: 'edit', code: 'debit_notes.edit', name: 'Edit Debit Notes', resource: 'Debit Notes' },
  { action: 'delete', code: 'debit_notes.delete', name: 'Delete Debit Notes', resource: 'Debit Notes' },
  { action: 'approve', code: 'debit_notes.approve', name: 'Approve Debit Notes', resource: 'Debit Notes' },
  { action: 'export', code: 'debit_notes.export', name: 'Export Debit Notes', resource: 'Debit Notes' },
  { action: 'view', code: 'files.view', name: 'View Files', resource: 'Files' },
  { action: 'upload', code: 'files.upload', name: 'Upload Files', resource: 'Files' },
  { action: 'download', code: 'files.download', name: 'Download Files', resource: 'Files' },
  { action: 'delete', code: 'files.delete', name: 'Delete Files', resource: 'Files' },
  { action: 'view', code: 'ledgers.view', name: 'View Ledgers', resource: 'Ledgers' },
  { action: 'export', code: 'ledgers.export', name: 'Export Ledgers', resource: 'Ledgers' },
  { action: 'download', code: 'ledgers.download', name: 'Download Ledger PDFs', resource: 'Ledgers' },
] as const;

export const defaultRolePermissionCodes: Record<string, string[]> = {
  accounts: [
    'work_orders.view',
    'ra_bills.view',
    'invoices.view',
    'invoices.verify',
    'payments.view',
    'payments.create',
    'payments.approve',
    'debit_notes.view',
    'ledgers.view',
    'ledgers.export',
    'files.view',
    'files.download',
  ],
  admin: contractPermissions.filter((permission) => permission.action !== 'delete').map((permission) => permission.code),
  approver: [
    'work_orders.view',
    'work_orders.approve',
    'ra_bills.view',
    'ra_bills.approve',
    'invoices.view',
    'payments.view',
    'debit_notes.view',
    'debit_notes.approve',
    'ledgers.view',
    'files.view',
    'files.download',
  ],
  company_owner: contractPermissions.filter((permission) => permission.action !== 'delete').map((permission) => permission.code),
  module_admin: contractPermissions.filter((permission) => permission.action !== 'delete').map((permission) => permission.code),
  platform_owner: contractPermissions.map((permission) => permission.code),
  project_manager: [
    'work_orders.view',
    'work_orders.create',
    'work_orders.edit',
    'ra_bills.view',
    'ra_bills.create',
    'ra_bills.edit',
    'invoices.view',
    'payments.view',
    'debit_notes.view',
    'files.view',
    'files.upload',
    'files.download',
    'ledgers.view',
    'ledgers.export',
  ],
  site_engineer: [
    'work_orders.view',
    'ra_bills.view',
    'ra_bills.create',
    'files.view',
    'files.upload',
    'files.download',
  ],
  staff: [
    'work_orders.view',
    'ra_bills.view',
    'invoices.view',
    'payments.view',
    'debit_notes.view',
    'files.view',
    'files.download',
  ],
  super_admin: contractPermissions.map((permission) => permission.code),
  vendor: ['work_orders.view', 'ra_bills.view', 'invoices.view', 'payments.view', 'files.view', 'files.download', 'ledgers.view', 'ledgers.download'],
  viewer: ['work_orders.view', 'ra_bills.view', 'invoices.view', 'payments.view', 'debit_notes.view', 'files.view', 'files.download', 'ledgers.view'],
};
